// File generated by FlutterFire CLI (androidStaging + forEnv added manually — keep on regen).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:petsfollow_mobile/core/config/app_env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Follows [AppEnv.value] (staging → androidStaging on Android).
  static FirebaseOptions get currentPlatform => forEnv(AppEnv.value);

  /// Android options follow [appEnv] (`staging` | `prod`); iOS unchanged for now.
  static FirebaseOptions forEnv(String appEnv) {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return appEnv == 'staging' ? androidStaging : android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZdvMc09Ev4ppCNS84bS5yiQRxqeUqrok',
    appId: '1:237481297060:android:cfda5c59a08bfd6dc9d231',
    messagingSenderId: '237481297060',
    projectId: 'premedica-prod-2025',
    storageBucket: 'premedica-prod-2025.firebasestorage.app',
  );

  /// Flavor staging — package `be.llitsc.petsfollow_mobile.staging`.
  static const FirebaseOptions androidStaging = FirebaseOptions(
    apiKey: 'AIzaSyBZdvMc09Ev4ppCNS84bS5yiQRxqeUqrok',
    appId: '1:237481297060:android:a15f2666e4707cf1c9d231',
    messagingSenderId: '237481297060',
    projectId: 'premedica-prod-2025',
    storageBucket: 'premedica-prod-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDomEWlkjZulMZfz7kATxeqQVwT73wUIfk',
    appId: '1:237481297060:ios:c921e9c056661daec9d231',
    messagingSenderId: '237481297060',
    projectId: 'premedica-prod-2025',
    storageBucket: 'premedica-prod-2025.firebasestorage.app',
    androidClientId: '237481297060-lc52m7hdkndrjlshfop8tcen57lpl992.apps.googleusercontent.com',
    iosClientId: '237481297060-5pq3v8a0n2t09dbl3igrg7cenvuha4d7.apps.googleusercontent.com',
    iosBundleId: 'be.llitsc.petsfollowMobile',
  );
}
