name: petsfollow_mobile
description: petsFollow — suivi santé de votre animal
publish_to: 'none'
version: 0.2.6+12

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  dio: ^5.7.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.3
  fl_chart: ^0.69.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  firebase_core: ^4.12.1
  image_picker: ^1.1.2
  http_parser: ^4.0.2
  flutter_svg: ^2.0.17
  in_app_review: ^2.0.10
  firebase_messaging: ^16.4.3
  flutter_timezone: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/brand/
