FROM node:22-alpine AS builder
WORKDIR /app
COPY nuxtjs/package*.json ./nuxtjs/
RUN cd nuxtjs && npm install
COPY nuxtjs ./nuxtjs
COPY brand ./brand
RUN cd nuxtjs && npm run build

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/nuxtjs/.output ./.output
ENV HOST=0.0.0.0
ENV PORT=3000
EXPOSE 3000
CMD ["node", ".output/server/index.mjs"]
