FROM golang:1.21-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /petsfollow-api ./cmd/petsfollow-api

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /petsfollow-api .
EXPOSE 8080
ENTRYPOINT ["/app/petsfollow-api"]
