DROP SCHEMA IF EXISTS notifications CASCADE;
DROP SCHEMA IF EXISTS messaging CASCADE;
DROP SCHEMA IF EXISTS heartrate CASCADE;
DROP SCHEMA IF EXISTS pets CASCADE;
DROP SCHEMA IF EXISTS practice CASCADE;
DROP SCHEMA IF EXISTS identity CASCADE;
