#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TOKENS="$ROOT/brand/tokens/design-tokens.json"

python3 <<'PY'
import json, pathlib
root = pathlib.Path("$ROOT".replace("$ROOT", __import__('os').environ.get('ROOT', '.')))
PY

ROOT_DIR="$ROOT"
python3 - "$ROOT_DIR" <<'PY'
import json, pathlib, sys
root = pathlib.Path(sys.argv[1])
tokens = json.loads((root / "brand/tokens/design-tokens.json").read_text())

css = f"""/* Generated by make brand-sync — do not edit */
:root {{
  --pf-brand-navy: {tokens['brand']['navy']};
  --pf-brand-teal: {tokens['brand']['teal']};
  --pf-brand-gold: {tokens['brand']['gold']};
  --pf-brand-sage: {tokens['brand']['sage']};
  --pf-brand-coral: {tokens['brand']['coral']};
  --pf-vet-bg: {tokens['pro']['bg']};
  --pf-vet-surface: {tokens['pro']['surface']};
  --pf-vet-primary: {tokens['pro']['primary']};
  --pf-vet-accent: {tokens['pro']['accent']};
  --pf-vet-alert: {tokens['pro']['alert']};
  --pf-vet-text: {tokens['pro']['text']};
  --pf-vet-text-muted: {tokens['pro']['textMuted']};
  --pf-vet-border: {tokens['pro']['border']};
  --pf-vet-radius: {tokens['pro']['radius']};
  --pf-vet-radius-lg: {tokens['pro']['radiusLg']};
  --pf-vet-radius-xl: {tokens['pro']['radiusXl']};
  --pf-vet-shadow-sm: {tokens['pro']['shadowSm']};
  --pf-vet-shadow-md: {tokens['pro']['shadowMd']};
  --pf-vet-sidebar-width: {tokens['pro']['sidebarWidth']};
  --pf-vet-content-max: {tokens['pro']['contentMaxWidth']};
  --pf-vet-gradient-login: {tokens['pro']['gradientLogin']};
  --pf-vet-gradient-main: {tokens['pro']['gradientMain']};
  --pf-vet-focus-ring: {tokens['pro']['focusRing']};
  --pf-vet-shadow-hover: {tokens['pro']['shadowHover']};
  --pf-font: {tokens['font']['sans']};
  --pf-font-mono: {tokens['font']['mono']};
}}
"""
(root / "nuxtjs/assets/css/tokens.css").write_text(css)

def hex_to_color(name, hex_val):
    h = hex_val.lstrip("#")
    return f"  static const {name} = Color(0xFF{h.upper()});"

pets = tokens["pets"]
brand = tokens["brand"]
dart_lines = [
    "// Generated by make brand-sync — do not edit",
    "import 'package:flutter/material.dart';",
    "",
    "abstract final class AppColors {",
    hex_to_color("brandNavy", brand["navy"]),
    hex_to_color("brandTeal", brand["teal"]),
    hex_to_color("brandGold", brand["gold"]),
    hex_to_color("brandSage", brand["sage"]),
    hex_to_color("brandCoral", brand["coral"]),
    hex_to_color("bg", pets["bg"]),
    hex_to_color("surface", pets["surface"]),
    hex_to_color("surfaceElevated", pets["surfaceElevated"]),
    hex_to_color("primary", pets["primary"]),
    hex_to_color("accent", pets["accent"]),
    hex_to_color("gold", pets.get("gold", brand["gold"])),
    hex_to_color("alert", pets["alert"]),
    hex_to_color("cream", pets["text"]),
    hex_to_color("textMuted", pets["textMuted"]),
    "}",
    "",
]
(root / "flutter/lib/core/theme/app_colors.dart").write_text("\n".join(dart_lines))

emblem_src = root / "brand/emblem/petsfollow-emblem.svg"
logo_src = root / "brand/logo/petsfollow-horizontal.svg"
emblem_nuxt = root / "nuxtjs/public/brand/emblem.svg"
flutter_brand = root / "flutter/assets/brand"
flutter_brand.mkdir(parents=True, exist_ok=True)
emblem_nuxt.parent.mkdir(parents=True, exist_ok=True)
emblem_nuxt.write_text(emblem_src.read_text())
(flutter_brand / "petsfollow-emblem.svg").write_text(emblem_src.read_text())
(flutter_brand / "petsfollow-horizontal.svg").write_text(logo_src.read_text())

print("→ brand-sync OK")
PY
