#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TOKENS="$ROOT/brand/tokens/design-tokens.json"

python3 <<'PY'
import json, pathlib
root = pathlib.Path("$ROOT".replace("$ROOT", __import__('os').environ.get('ROOT', '.')))
PY

ROOT_DIR="$ROOT"
python3 - "$ROOT_DIR" <<'PY'
import json, pathlib, sys
root = pathlib.Path(sys.argv[1])
tokens = json.loads((root / "brand/tokens/design-tokens.json").read_text())

css = f"""/* Generated by make brand-sync — do not edit */
:root {{
  --pf-brand-navy: {tokens['brand']['navy']};
  --pf-brand-teal: {tokens['brand']['teal']};
  --pf-brand-gold: {tokens['brand']['gold']};
  --pf-brand-sage: {tokens['brand']['sage']};
  --pf-brand-coral: {tokens['brand']['coral']};
  --pf-vet-bg: {tokens['pro']['bg']};
  --pf-vet-surface: {tokens['pro']['surface']};
  --pf-vet-primary: {tokens['pro']['primary']};
  --pf-vet-accent: {tokens['pro']['accent']};
  --pf-vet-alert: {tokens['pro']['alert']};
  --pf-vet-text: {tokens['pro']['text']};
  --pf-vet-text-muted: {tokens['pro']['textMuted']};
  --pf-vet-border: {tokens['pro']['border']};
  --pf-vet-radius: {tokens['pro']['radius']};
  --pf-vet-radius-lg: {tokens['pro']['radiusLg']};
  --pf-vet-radius-xl: {tokens['pro']['radiusXl']};
  --pf-vet-shadow-sm: {tokens['pro']['shadowSm']};
  --pf-vet-shadow-md: {tokens['pro']['shadowMd']};
  --pf-vet-sidebar-width: {tokens['pro']['sidebarWidth']};
  --pf-vet-content-max: {tokens['pro']['contentMaxWidth']};
  --pf-vet-gradient-login: {tokens['pro']['gradientLogin']};
  --pf-vet-gradient-main: {tokens['pro']['gradientMain']};
  --pf-vet-focus-ring: {tokens['pro']['focusRing']};
  --pf-vet-shadow-hover: {tokens['pro']['shadowHover']};
  --pf-font: {tokens['font']['sans']};
  --pf-font-mono: {tokens['font']['mono']};
}}
"""
(root / "nuxtjs/assets/css/tokens.css").write_text(css)

dart = f"""// Generated by make brand-sync — do not edit
import 'package:flutter/material.dart';

abstract final class AppColors {{
  static const brandNavy = Color(0xFF1B3A4B);
  static const brandTeal = Color(0xFF2A9D8F);
  static const brandGold = Color(0xFFE9C46A);
  static const brandSage = Color(0xFF52B788);
  static const brandCoral = Color(0xFFF4A261);
  static const bg = Color(0xFF0D1B2A);
  static const surface = Color(0xFF1B2838);
  static const primary = Color(0xFF52B788);
  static const accent = Color(0xFFF4A261);
  static const cream = Color(0xFFFEFAE0);
  static const textMuted = Color(0xFF94A3B8);
}}
"""
(root / "flutter/lib/core/theme/app_colors.dart").write_text(dart)

emblem_src = root / "brand/emblem/petsfollow-emblem.svg"
emblem_nuxt = root / "nuxtjs/public/brand/emblem.svg"
emblem_nuxt.parent.mkdir(parents=True, exist_ok=True)
emblem_nuxt.write_text(emblem_src.read_text())

print("→ brand-sync OK")
PY
